### ISSUE TITLE
Permission to modify and distribute

### ISSUE THREAD

**Issue by JulianPrieber** [D3FaltXD/tree#1]
Hey @D3FaltXD,
awesome project!

I'd love to adapt this to be a [theme](https://github.com/JulianPrieber/llc-themes) for our project [LittleLink Custom](https://github.com/JulianPrieber/littlelink-custom).

Since you did not include a [license](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository), **I would first like to ask your approval in order to use your work**.

Visit our [website](https://littlelink-custom.com/) to learn more about the project if you're interested.
If you want to talk to me directly, feel free to join our [Discord](https://discord.littlelink-custom.com/).

**Comment by D3FaltXD** [comment]
Hey there, 
sure go ahead with it! really happy being part of Little links.
Also mb, imma add the license asap

**Comment by JulianPrieber** [comment]
Awesome, tysm

**Comment by JulianPrieber** [comment]
_https://github.com/JulianPrieber/Magic-Kingdom_
